INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:[<RememberedBrandForm bound=False, valid=Unknown, fields=(experience;brand;scenes_description;emotions;seen_objects;audio;caption;used_brand;used_product;usage_brand;usage_product;brand_ads_seen;ad_seen)>, <RememberedBrandForm bound=False, valid=Unknown, fields=(experience;brand;scenes_description;emotions;seen_objects;audio;caption;used_brand;used_product;usage_brand;usage_product;brand_ads_seen;ad_seen)>, <RememberedBrandForm bound=False, valid=Unknown, fields=(experience;brand;scenes_description;emotions;seen_objects;audio;caption;used_brand;used_product;usage_brand;usage_product;brand_ads_seen;ad_seen)>, <RememberedBrandForm bound=False, valid=Unknown, fields=(experience;brand;scenes_description;emotions;seen_objects;audio;caption;used_brand;used_product;usage_brand;usage_product;brand_ads_seen;ad_seen)>]
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
INFO:root:4
INFO:root:4
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
INFO:root:4
INFO:root:10
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
INFO:root:4
INFO:root:11
INFO:root:<django.forms.models.ModelChoiceField object at 0x7fc631a18bb0>
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
ERROR:django.request:Internal Server Error: /form/brand/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/questions.py", line 165, in brand_survey
    curr_form = forms[page_number-1]
TypeError: unsupported operand type(s) for -: 'str' and 'int'
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:2
INFO:root:2
INFO:root:2
INFO:root:2
ERROR:django.request:Internal Server Error: /form/brand/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/questions.py", line 168, in brand_survey
    return render(request, "brand_survey.html", {"form": curr_form, "has_next": has_next})
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 50: 'endfor'. Did you forget to register or load this tag?
INFO:root:2
INFO:root:2
INFO:root:2
INFO:root:2
INFO:root:2
INFO:root:2
ERROR:django.request:Internal Server Error: /form/brand/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/questions.py", line 166, in brand_survey
    curr_form = forms[page_number-1]
IndexError: list index out of range
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:2
INFO:root:2
INFO:root:2
INFO:root:2
INFO:root:2
