INFO:root:<ul class="errorlist"><li>user<ul class="errorlist"><li>Survey with this User already exists.</li></ul></li></ul>
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/intro.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:<ul class="errorlist"><li>user<ul class="errorlist"><li>Survey with this User already exists.</li></ul></li></ul>
INFO:root:<ul class="errorlist"><li>user<ul class="errorlist"><li>Survey with this User already exists.</li></ul></li></ul>
INFO:root:3
ERROR:django.request:Internal Server Error: /form/brand/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/questions.py", line 202, in brand_survey
    page_number = int(request.GET.get("page"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
INFO:root:3
